import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/src/styles/Home.module.scss";
import Hero from "../components/hero/Hero";
import Gallery from "../components/gallery/Gallery";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Hero />
        <Gallery />
      </main>
    </>
  );
}
