const products = [
    {
    "id": 1,
    "title": "Advance Veterinary Diets Crocchette per cani",
    "description": "Crocchette dietetiche complete e bilanciate Advance Veterinary Diets, in diverse varianti per accompagnare il trattamento medico dei cani che soffrono di diverse patologie.",
    "animal": "dog",
    "price": 66.20,
    "discountPercentage": 30,
    "rating": 4.69,
    "stock": 94,
    "brand": "Advance",
    "category": "cibo per cani",
    "categoryImage": "./img/dog_food/catimg.jpg",
    "image": "./img/dog_food/advance_urinary.png"
    },
    {
    "id": 2,
    "title": "Almo Nature Holistic Crocchette per gatti",
    "description": "Almo Nature Holistic è un alimento secco completo e bilanciato per gatti adulti e gattini, gustoso e amato dai gatti di tutte le razze e di tutte le età.",
    "animal": "cat",
    "price": 41.60,
    "discountPercentage": 50,
    "rating": 4.70,
    "stock": 50,
    "brand": "Almo Nature",
    "category": "cibo per gatti",
    "categoryImage": "./img/cat_food/catimg.jpg",
    "image": "./img/cat_food/almo_nature.png"
    },
    {
    "id": 3,
    "title": "Set di giochi per cani Riccio",
    "description": "Set di 5 giochi per cani, contenente un riccio in canvas, un cuscinetto con corda, un osso in TPR con punte e due palline da tennis, con squeak integrato in osso, riccio e cuscinetto.",
    "animal": "dog",
    "price": 10,
    "discountPercentage": 10,
    "rating": 3,
    "stock": 50,
    "brand": "Riccio",
    "category": "giochi",
    "categoryImage": "./img/giochi/catimg.png",
    "image": "./img/giochi/set.PNG"
    },
    {
    "id": 4,
    "title": "Sacchetti igienici biodegradabili",
    "description": "Pratici ed ecologici: questi Sacchetti igienici biodegradabili privi di odore sono realizzati in amido di mais, compostabile e biodegradabile e soddisfano le linee guida europee sui materiali compostabili.",
    "animal": "dog",
    "price": 3.29,
    "discountPercentage": 5,
    "rating": 4.7,
    "stock": 50,
    "brand": "Zoolove",
    "category": "igiene",
    "categoryImage": "./img/igiene/catimg.jpg",
    "image": "./img/igiene/sacchetti_igienici.PNG"
    },
    {
    "id": 5,
    "title": "Cuscino Smilla",
    "description": "Cuscino Smilla per gatti, cuccioli e cani di piccola taglia, con bordo rialzato e morbida imbottitura. Lavabile a 30°C. Colore: arancio e impronta di zampina bianca.",
    "animal": "dog",
    "price": 9,
    "discountPercentage": 20,
    "rating": 3.5,
    "stock": 50,
    "brand": "Smilla",
    "category": "accessori",
    "categoryImage": "./img/accessori/catimg.jpg",
    "image": "./img/accessori/cuscino_similla.PNG"
    },
    {
    "id": 6,
    "title": "Exspot Spot-on per cani",
    "description": "Exspot è un antiparassitario per cani (a partire dai 4 mesi di vita) per uso cutaneo, specifico per il trattamento delle infestazioni da pulci, zecche e zanzare.",
    "animal": "dog",
    "price": 30,
    "discountPercentage": 25,
    "rating": 4.9,
    "stock": 50,
    "brand": "Exspot",
    "category": "salute",
    "categoryImage": "./img/salute/catimg.jpg",
    "image": "./img/salute/exspot.PNG"
    },
    {
    "id": 7,
    "title": "Almo Nature Holistic Crocchette per cani",
    "description": "La formulazione bilanciata di queste crocchette soddisfa al meglio il fabbisogno nutrizionale naturale del cane. Almo Nature è arricchito con una speciale miscela di nutraceutici che lo rendono particolarmente adatto a cani con problemi di ipersensibilità alimentare.",
    "animal": "dog",
    "price": 34.09,
    "discountPercentage": 30,
    "rating": 4.5,
    "stock": 50,
    "brand": "Almo Nature",
    "category": "cibo per cani",
    "categoryImage": "./img/dog_food/catimg.jpg",
    "image": "./img/dog_food/almo_nature.PNG"
    },
    {
    "id": 8,
    "title": "Purina ONE crocchette per gatti",
        "description": " L'alimento secco Purina ONE si contraddistingue per il suo elevato contenuto di nutrienti, vitamine e minerali che contribuisce alla salute e alla vitalità del gatto. Inoltre la sua formula è stata specificamente studiata per supportare le difese immunitarie naturali dell'animale. ",
    "animal": "cat",
    "price": 12.59,
    "discountPercentage": 15,
    "rating": 4.5,
    "stock": 50,
    "brand": "Purina",
    "category": "cibo per gatti",
    "categoryImage": "./img/cat_food/catimg.jpg",
    "image": "./img/cat_food/purina.PNG"
    },
]

export default products;